/* This file is automagically generated by build. Do NOT edit. */

#define VERSION_BUILD  31
#define VERSION_USER   "lundman"
#define VERSION_HOST   "shinken.interq.or.jp"
#define VERSION_DATE   "Fri Jan  1 09:45:01 2010"
#define VERSION_STRING "lundman@shinken.interq.or.jp build 31 (Fri Jan  1 09:45:01 2010)"

/* Lundtastic services */
